/*
 * Copyright (c) 2024. Devtron Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

-- Migration: Create tables for RAG documentation
-- Description: Sets up the database schema for Devtron documentation RAG system
-- Version: 2
-- Date: 2026-01-19
-- Note: pgvector extension is enabled in startup.sh before migrations run

-- Create documents table
-- This table stores documentation chunks with their vector embeddings
CREATE TABLE IF NOT EXISTS "public"."documents"
(
    "id"          TEXT                     NOT NULL,
    "title"       TEXT                     NOT NULL,
    "source"      TEXT                     NOT NULL,
    "header"      TEXT,
    "content"     TEXT                     NOT NULL,
    "chunk_index" INTEGER,
    "embedding"   vector(1024),  -- BAAI/bge-large-en-v1.5 produces 1024-dimensional vectors
    "created_at"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

-- Create index for vector similarity search using IVFFlat
-- IVFFlat is faster for large datasets (uses approximate nearest neighbor)
CREATE INDEX IF NOT EXISTS documents_embedding_idx
    ON "public"."documents" USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

-- Create index for source lookups (for incremental updates)
CREATE INDEX IF NOT EXISTS documents_source_idx
    ON "public"."documents"(source);

-- Create index for title searches
CREATE INDEX IF NOT EXISTS documents_title_idx
    ON "public"."documents"(title);

-- Create migration tracking table
CREATE TABLE IF NOT EXISTS "public"."schema_migrations"
(
    "version"     TEXT                     NOT NULL,
    "applied_at"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "description" TEXT,
    PRIMARY KEY ("version")
);

-- Record this migration
INSERT INTO "public"."schema_migrations" (version, description)
VALUES ('2', 'Initialize pgvector extension and create documents table for RAG')
ON CONFLICT (version) DO NOTHING;

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to auto-update updated_at
DROP TRIGGER IF EXISTS update_documents_updated_at ON "public"."documents";
CREATE TRIGGER update_documents_updated_at
    BEFORE UPDATE ON "public"."documents"
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Create view for document statistics
CREATE OR REPLACE VIEW document_stats AS
SELECT
    COUNT(*) as total_documents,
    COUNT(DISTINCT source) as unique_sources,
    COUNT(DISTINCT title) as unique_titles,
    MIN(created_at) as first_indexed,
    MAX(updated_at) as last_updated
FROM "public"."documents";

-- Add comments for documentation
COMMENT ON TABLE "public"."documents" IS 'Stores documentation chunks with vector embeddings for semantic search';
COMMENT ON COLUMN "public"."documents"."id" IS 'Unique identifier for document chunk (format: {doc_id}_chunk_{index})';
COMMENT ON COLUMN "public"."documents"."embedding" IS 'Vector embedding (1024-dim) generated by BAAI/bge-large-en-v1.5';
COMMENT ON COLUMN "public"."documents"."source" IS 'Source file path in the documentation repository';
COMMENT ON COLUMN "public"."documents"."header" IS 'Section header or title of the chunk';
COMMENT ON INDEX documents_embedding_idx IS 'IVFFlat index for fast approximate nearest neighbor search';

