// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devtron-labs/central-api/api"
	"github.com/devtron-labs/central-api/client"
	"github.com/devtron-labs/central-api/internal/logger"
	"github.com/devtron-labs/central-api/pkg"
)

// Injectors from Wire.go:

func InitializeApp() (*App, error) {
	sugaredLogger := logger.NewSugardLogger()
	gitHubClient, err := util.NewGitHubClient(sugaredLogger)
	if err != nil {
		return nil, err
	}
	releaseCache := util.NewReleaseCache(sugaredLogger)
	moduleConfig, err := util.NewModuleConfig(sugaredLogger)
	if err != nil {
		return nil, err
	}
	releaseNoteServiceImpl := pkg.NewReleaseNoteServiceImpl(sugaredLogger, gitHubClient, releaseCache, moduleConfig)
	webhookSecretValidatorImpl := pkg.NewWebhookSecretValidatorImpl(sugaredLogger, gitHubClient)
	ciBuildMetadataServiceImpl := pkg.NewCiBuildMetadataServiceImpl(sugaredLogger)
	restHandlerImpl := api.NewRestHandlerImpl(sugaredLogger, releaseNoteServiceImpl, webhookSecretValidatorImpl, gitHubClient, ciBuildMetadataServiceImpl)
	muxRouter := api.NewMuxRouter(sugaredLogger, restHandlerImpl)
	app := NewApp(muxRouter, sugaredLogger)
	return app, nil
}
