// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devtron-labs/central-api/api"
	currency2 "github.com/devtron-labs/central-api/api/currency"
	"github.com/devtron-labs/central-api/client"
	"github.com/devtron-labs/central-api/internal/logger"
	"github.com/devtron-labs/central-api/pkg"
	"github.com/devtron-labs/central-api/pkg/currency"
	"github.com/devtron-labs/common-lib/blob-storage"
)

// Injectors from Wire.go:

func InitializeApp() (*App, error) {
	sugaredLogger, err := logger.NewSugaredLogger()
	if err != nil {
		return nil, err
	}
	gitHubClient, err := util.NewGitHubClient(sugaredLogger)
	if err != nil {
		return nil, err
	}
	moduleConfig, err := util.NewModuleConfig(sugaredLogger)
	if err != nil {
		return nil, err
	}
	blobConfigVariables, err := util.NewBlobConfig(sugaredLogger)
	if err != nil {
		return nil, err
	}
	blobStorageServiceImpl := blob_storage.NewBlobStorageServiceImpl(sugaredLogger)
	releaseNoteServiceImpl, err := pkg.NewReleaseNoteServiceImpl(sugaredLogger, gitHubClient, moduleConfig, blobConfigVariables, blobStorageServiceImpl)
	if err != nil {
		return nil, err
	}
	webhookSecretValidatorImpl := pkg.NewWebhookSecretValidatorImpl(sugaredLogger, gitHubClient)
	ciBuildMetadataServiceImpl := pkg.NewCiBuildMetadataServiceImpl(sugaredLogger)
	restHandlerImpl := api.NewRestHandlerImpl(sugaredLogger, releaseNoteServiceImpl, webhookSecretValidatorImpl, gitHubClient, ciBuildMetadataServiceImpl)
	currencyConfig, err := currency.NewCurrencyConfig(sugaredLogger)
	if err != nil {
		return nil, err
	}
	currencyServiceImpl := currency.NewServiceImpl(currencyConfig, sugaredLogger)
	currencyRestHandlerImpl := currency2.NewCurrencyRestHandlerImpl(sugaredLogger, currencyServiceImpl)
	currencyRouter := currency2.NewRouter(sugaredLogger, currencyRestHandlerImpl)
	muxRouter := api.NewMuxRouter(sugaredLogger, restHandlerImpl, currencyRouter)
	app := NewApp(muxRouter, sugaredLogger)
	return app, nil
}
